### ISSUE TITLE
fix for php 7

### ISSUE THREAD

**Issue by MrSwed** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddMultipleFields#13]
[here](https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddMultipleFields/blob/master/ddmultiplefields/ddmultiplefields.php#L130-L132)  is error on php 7
http://modx.im//blog/addons/4265.html#comment44232

**Comment by Ronef** [comment]
b038648290aa03d1ae9bb44b637509948766c9c0
