### ISSUE TITLE
Нет подтверждения при клике на крестик (очистить все поля)

### ISSUE THREAD

**Issue by mediakot** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddMultipleFields#3]
В неудачном месте кнопка удаления всех записей "х", да к тому же нет подтверждения. Я добавил алерт. Заменил в файле jquery.ddMM.mm_ddMultipleFields.js
`$(".ddDeleteButton"+(_inst.minRow?":gt("+(_inst.minRow-1)+")":""), $ddMultipleField).click();`

на

`if(confirm("Вы уверены?"))$(".ddDeleteButton"+(_inst.minRow?":gt("+(_inst.minRow-1)+")":""), $ddMultipleField).click();`

**Comment by MrSwed** [comment]
@mediakot Пока не принято в официальный репозитарий :(
сделайте PR в ветку develop [репозитария, где это сделано](https://github.com/MrSwed/MODXEvo.plugin.ManagerManager.mm_ddMultipleFields)

**Comment by MrSwed** [comment]
@mediakot сделал PR не в тот репозитарий (см. ссылка в предыдущем комментарии) и собственно где изменения ?

**Comment by MrSwed** [comment]
подтверждение не делал, т.к. есть предупреждающая подсказка и возможность  восстановления исходного состояния кнопкой Reset. Впрочем, если изменения не были сохранены перед очисткой, восстановить их уже не получится.
