### ISSUE TITLE
Не добавляются поля...

### ISSUE THREAD

**Issue by sashabeep** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddMultipleFields#5]
Странное происходит, modx 1.1 официалка, managerManager 0.6.2, виджет 4.6
При добавлении строки можно выбрать картинку только 1 раз.

Очень странное поведение, не на одном компе...
Другой разработчик говорит, что контент пропадает. Есть ли ограничение на длину? Тип TV пробовал разный, image, textarea...

в Firefox и Сhrome поведение одинаковое - приходится заполнять по 1 строчке за раз
https://www.youtube.com/watch?v=ys3c0J9IK_g

**Comment by MrSwed** [comment]
похоже глюк с одинаковыми подряд файлами, проверьте с разными изображениями..
в реальности нет смысла вставлять nophoto - это делается через phpthumb (если нет изображения в нем по умолчанию подставляется)

**Comment by sashabeep** [comment]
Да, с разными именами файлов нет глюка, окно открывается и пусть вставляет.
Пустой файл использовал для проверки, а не как заглушку, разумеется.

**Comment by Ronef** [comment]
@sashabeep А это на оригинальной версии виджета или на той, что с 1.1 шла?
